-- users table
CREATE TABLE IF NOT EXISTS PLAYER_REVIEWS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  ownerId TEXT NOT NULL,
  playerName TEXT NOT NULL,
  eventName TEXT NOT NULL,
  imageReview TEXT,
  reviewee TEXT,
  alt1 TEXT,
  alt2 TEXT,
  alt3 TEXT,
  pros TEXT NOT NULL,
  cons TEXT NOT NULL,
  verdict TEXT NOT NULL,
  rating FLOAT NOT NULL,
  rlink TEXT,
  playerReviews_players TEXT,
  urlReview TEXT,
  partnerId TEXT,
  partnerName TEXT,
  partnerUrl TEXT,
  playerReviews_list TEXT,
  playerReviews_item TEXT,
  stats1 INTEGER NOT NULL,
  stats2 INTEGER NOT NULL,
  stats3 INTEGER NOT NULL,
  stats4 INTEGER NOT NULL,
  stats5 INTEGER NOT NULL,
  stats6 INTEGER NOT NULL,
  st_type1 TEXT NOT NULL,
  st_type2 TEXT NOT NULL,
  st_type3 TEXT NOT NULL,
  st_type4 TEXT NOT NULL,
  st_type5 TEXT NOT NULL,
  st_type6 TEXT NOT NULL,
  skillImage1 TEXT,
  skillImage2 TEXT,
  skillImage3 TEXT,
  skillImage4 TEXT,
  skillImage5 TEXT,
  skillImage6 TEXT,
  skill1 TEXT,
  skill2 TEXT,
  skill3 TEXT,
  skill4 TEXT,
  skill5 TEXT,
  skill6 TEXT,
  wf_1 TEXT,
  sm1 TEXT,
  st1 TEXT,
  pos TEXT,
  rev_cred TEXT,
  rev_cred_url TEXT,
  urlSlugCopy TEXT
);

