-- users table
CREATE TABLE IF NOT EXISTS PLAYER_REVIEWS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  playerName TEXT NOT NULL,
  pos TEXT NOT NULL,
  imageReview TEXT,
  urlSlugCopy TEXT
  eventName TEXT NOT NULL,
  wf_1 TEXT,
  sm1 TEXT,
  st1 TEXT,
  alt1 TEXT,
  alt2 TEXT,
  alt3 TEXT,
  pros TEXT NOT NULL,
  cons TEXT NOT NULL,
  verdict TEXT NOT NULL,
  rating FLOAT NOT NULL,
  stats1 INTEGER NOT NULL,
  stats2 INTEGER NOT NULL,
  stats3 INTEGER NOT NULL,
  stats4 INTEGER NOT NULL,
  stats5 INTEGER NOT NULL,
  stats6 INTEGER NOT NULL,
  skill1 TEXT,
  skill2 TEXT,
  skill3 TEXT,
  skill4 TEXT,
  skill5 TEXT,
  skill6 TEXT,
  skillImage1 TEXT,
  skillImage2 TEXT,
  skillImage3 TEXT,
  skillImage4 TEXT,
  skillImage5 TEXT,
  skillImage6 TEXT,
  st_type1 TEXT NOT NULL,
  st_type2 TEXT NOT NULL,
  st_type3 TEXT NOT NULL,
  st_type4 TEXT NOT NULL,
  st_type5 TEXT NOT NULL,
  st_type6 TEXT NOT NULL,
  playerReviews_item TEXT,
);

