INSERT INTO PLAYER_REVIEWS (
  ownerId,
  playerName,
  eventName,
  imageReview,
  reviewee,
  alt1,
  alt2,
  alt3,
  pros,
  cons,
  verdict,
  rating,
  rlink,
  playerReviews_players,
  urlReview,
  partnerId,
  partnerName,
  partnerUrl,
  playerReviews_list,
  playerReviews_item,
  stats1,
  stats2,
  stats3,
  stats4,
  stats5,
  stats6,
  st_type1,
  st_type2,
  st_type3,
  st_type4,
  st_type5,
  st_type6,
  skillImage1,
  skillImage2,
  skillImage3,
  skillImage4,
  skillImage5,
  skillImage6,
  skill1,
  skill2,
  skill3,
  skill4,
  skill5,
  skill6,
  wf_1,
  sm1,
  st1,
  pos,
  rev_cred,
  rev_cred_url,
  urlSlugCopy
) VALUES (
  'user_123',
  'Lionel Messi',
  'Champions League Final',
  'images/reviews/messi-review.png',
  'Expert Analyst',
  'Messi dribbling',
  'Messi passing',
  'Messi shooting',
  'Exceptional dribbling, elite vision, match-winning ability',
  'Low aerial presence, limited defensive contribution',
  'A legendary performance that decided the game',
  9.5,
  'https://example.com/full-review',
  'messi',
  'https://example.com/reviews/messi',
  'partner_001',
  'Football Analytics',
  'https://footballanalytics.example',
  'top-players',
  'messi-review-item',
  95,
  92,
  91,
  88,
  90,
  93,
  'Pace',
  'Shooting',
  'Passing',
  'Dribbling',
  'Defending',
  'Physical',
  'images/skills/pace.png',
  'images/skills/shooting.png',
  'images/skills/passing.png',
  'images/skills/dribbling.png',
  'images/skills/defending.png',
  'images/skills/physical.png',
  'Elite Pace',
  'Deadly Finishing',
  'Creative Passing',
  'Close Control',
  'Smart Pressing',
  'Strong Balance',
  '4★',
  '5★',
  '99',
  'RW',
  'John Doe',
  'https://example.com/authors/john-doe',
  'lionel-messi-champions-league-final-review'
);
